### ISSUE TITLE
Jak wczytywać dane?

### ISSUE THREAD

**Issue by pbiecek** [pbiecek/Przewodnik#21]
Na bazie R, PD i RiBD

**Comment by pbiecek** [comment]
[*] Może w sekcji jak wczytać dane z Excela warto też coś wspomnieć w pakiecie readxl::read_excel.
Funkcja z tego pakietu ma swoje atuty:
- odczytuje starsze wersje plików z rozszerzeniem .xls (openxlsx nie),
- jest chyba trochę szybszy od openxlsx,

https://cran.r-project.org/web/packages/readxl/README.html

Moim zdaniem te dwa pakiety to najlepsze rozwiązania do odczytu danych z Excela - można je stosować zamiennie w zależności od potrzeb.

**Comment by BERENZ** [comment]
Może tutaj coś jeszcze znajdziesz ciekawego http://gastonsanchez.com/teaching/ w części "Getting Data From the Web with R". Swoją drogą prezentacje ma zrobione świetnie :D
